### ISSUE TITLE
Adjustment in documentation?

### ISSUE THREAD

**Issue by DMFSaint** [unsoluble/fvtt-macros#6]
Just downloaded and tried to use this but I have EXTREMELY limited experience with JSON, Foundry, etc. Took me a bit, but since I was using this for a Call of Cthulhu system the Actor, Item, and Adventure compendiums didn't show up in Foundry. Maybe add a note somewhere for people like me who don't know you need to change

`"system": "dnd5e", `

to CoC7 or whatever you're using?

**Comment by unsoluble** [comment]
Yeah this isn't documented _at all_ currently, is just meant as an example to start with. Most people should be using the [bespoke creation tool](https://fgen-mxzf-prod.herokuapp.com/module/create) to generate these.
